---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
spec:
  project: platform
  source:
    chart: kyverno-policies
    repoURL: https://kyverno.github.io/kyverno/
    targetRevision: 3.5.2
    helm:
      releaseName: kyverno-policies
      valuesObject:
        validationFailureAction: enforce
        background: true
        podSecurityStandard: restricted
        podSecuritySeverity: medium
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
